apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: mysqls.otus.homework

spec:
# Область видимости ресурса (namespaced or cluster)
  scope: Namespaced
# группа API ( Имя которое мы будем использовать в apiVersion )
  group: otus.homework
# определение имен нашего кастомниго ресурса
  names:
    kind: MySQL
# имя в единственном числе
    singular: mysql
# имя отображаемое при выводе
    plural: mysqls
    shortNames:
      - mysql
      - sql
      - db
  versions:
    - name: v1
      served: true
      storage: true
# параметры нашего объекта которые будут в спецификации
      schema:
        openAPIV3Schema:
          type: object
          properties:

            spec:
              type: object
              properties:
                image:
                  type: string
                database:
                  type: string
                password:
                  type: string
                storage_size:
                  type: string
              required:
                - image
                - database
                - password
                - storage_size
# status:
