apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-operator
  namespace: homework
spec:
  selector:
    matchLabels:
      app: otus-mysql-operator
  template:
    metadata:
      labels:
        app: otus-mysql-operator
    spec:
      serviceAccountName: otus
      containers:
      - name: mysql-operator
        image: roflmaoinmysoul/mysql-operator:1.0.0
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"

