{{- with .Values.ingress}}
{{- if .enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ing-webserver
  namespace: {{ $.Values.namespace }}
  annotations:
  {{- include "ingress.annotation" . }}
spec:
  ingressClassName: {{ .className }}
  rules:
  {{- range .hosts }}
  - host: {{ .host }}
    http:
      paths:
        {{- range .paths }}
        - pathType: {{ .pathType }}
          path: {{ .path }}
          backend:
            service:
              name: svc-webserver
              port: 
                number: 80
        {{- end }}        
  {{- end -}}
  {{- end }}
{{- end }}                
