
apiVersion: v1
kind: ServiceAccount
metadata:
  name: monitoring
  namespace: {{ .Values.namespace }}
secrets:
  - name: monitoring-secret-homework 
---
apiVersion: v1
kind: Secret
metadata:
  name: monitoring-secret-homework # имя секрета для использования пользователем "monitoring"
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: monitoring
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metrics-read-homework
rules:
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"] 
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: monitiring_user_homework
subjects:
  - kind: ServiceAccount
    name: monitoring
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: metrics-read-homework
  apiGroup: rbac.authorization.k8s.io
---
# второй пользователь который должен быть admin
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cd
  namespace: {{ .Values.namespace }}
secrets:
  - name: cd-secrets-homework
---
apiVersion: v1
kind: Secret
metadata:
  name: cd-secrets-homework # имя секрета для использования пользователем "cd"
  namespace: {{ .Values.namespace }}
  annotations:
    kubernetes.io/service-account.name: cd
type: kubernetes.io/service-account-token
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: cd-admin-homework
  namespace: {{ .Values.namespace }}
subjects:
  - kind: ServiceAccount
    name: cd
    namespace: {{ .Values.namespace }}
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io