apiVersion: v1
kind: Service
metadata:
  name: svc-webserver
  namespace: {{ .Values.namespace }}
  labels:
    HW: kuber-homework
spec:
  type: {{ .Values.service.type }}
  selector:
    HW: kuber-homework
  ports:
    - protocol: TCP
      targetPort: {{ .Values.app.network.port}}
      port: {{ .Values.service.port}}
