apiVersion: v1
kind: Service
metadata:
  name: svc-webserver
  namespace: homework
  labels:
    HW: kuber-homework
spec:
  type: ClusterIP
  selector:
    HW: kuber-homework
  ports:
    - protocol: TCP
      targetPort: 8000
      port: 80
