---
apiVersion: v1
kind: Service
metadata:
  name: svc-webserver
spec:
  type: ClusterIP
  selector:
    app: nginx
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
    - protocol: TCP
      port: 9113
      targetPort: 9113
