apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-homework
  namespace: homework
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
#  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /mnt/pv-homework

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-homework
  namespace: homework
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi

