apiVersion: v1
kind: ConfigMap
metadata:
  name: cmap-webserver
  namespace: homework
  labels:
    HW: kubernetes-intro
data:
  nginx.conf: |
    events {}
    http {
      server {
          listen 8000;
          root /homework;

          location / {
            autoindex on;
          }
      }
    }
---
apiVersion: v1
kind: Service
metadata:
  name: svc-webserver
  namespace: homework
  labels:
    HW: kubernetes-intro
spec:
  selector:
    name: webserver
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000

---
apiVersion: v1
kind: Pod
metadata:
  name: webserver
  namespace: homework
  labels:
    name: webserver
    HW: kubernetes-intro
spec:
  volumes:
    - name: vol-httproot
      emptyDir: {}
    - name: vol-nginx-config
      configMap:
        name: cmap-webserver 
  initContainers:
    - name: initindex
      image: alpine
      volumeMounts:
        - name: vol-httproot
          mountPath: "/init"
      command:
        - /bin/sh
        - -c
        - |
          echo "My index html from HW 1" > /init/index.html

  containers:
    - name: webserver
      image: nginx
      ports:
        - containerPort: 8000
      volumeMounts:
        - name: vol-httproot
          mountPath: "/homework"
        - name: vol-nginx-config
          mountPath: /etc/nginx/nginx.conf
          subPath: nginx.conf
      lifecycle:
        preStop:
          exec:
            command:
              - /bin/sh
              - -c
              - |
                rm -f /homework/index.html
